/**
 * Meridian Pantry about page: an editorial, source-led expression of the approved company story,
 * mission, vision and values for Karossy Foods Limited.
 */
import { ArrowUpRight, CircleDotDashed, HandHeart, ShieldCheck, Sprout, Waves } from "lucide-react";
import { Link } from "wouter";
import { PageLead, SiteFooter, SiteHeader } from "@/components/SiteLayout";

const traceImage = "/manus-storage/karossy-traceability_25ffa369.jpg";
const purposeImage = "/manus-storage/sales-girl_4f7b3698.jpg";
const values = [{ icon: Sprout, title: "Authenticity", copy: "We preserve the character and culinary identity of Nigerian and African foods." }, { icon: ShieldCheck, title: "Quality", copy: "We approach supply with a clear focus on suitable products and dependable sourcing." }, { icon: CircleDotDashed, title: "Integrity", copy: "We communicate the right details clearly, including what must be verified before supply." }, { icon: HandHeart, title: "Reliability", copy: "We want customers to experience a responsive, customer-centred supply relationship." }, { icon: Waves, title: "Customer focus", copy: "We shape conversations around your product, market and commercial requirements." }, { icon: ArrowUpRight, title: "Growth", copy: "We are building a trusted international name for Nigerian and African food sourcing and supply." }];

export default function About() {
  return <div className="app-shell page-shell"><SiteHeader /><main><PageLead eyebrow="About us" title={<>Connecting authentic African foods with the world.</>} description="Karossy Foods Limited is focused on sourcing, supplying and connecting customers with authentic Nigerian and African food products." bannerImage={traceImage} bannerPosition="center 46%" bannerVariant="about" />
    <section className="origin-story section-pad"><div className="site-shell origin-story-grid"><div className="origin-image origin-image-purpose"><img src={purposeImage} alt="Customer selecting fresh produce in a market" /><div className="vertical-caption">Food for every table</div></div><div className="origin-copy"><div className="route-kicker"><span /> Our purpose</div><h2>African food should be accessible wherever people live.</h2><p>We work to connect quality food products from Nigeria with consumers, retailers, restaurants, wholesalers, distributors and international buyers.</p><p>Our work begins with authentic products and continues through the attention paid to supply, product fit and the people who rely on them.</p><Link href="/contact" className="text-button">Talk to Karossy Foods <ArrowUpRight size={17} /></Link></div></div></section>
    <section className="mission-section"><div className="site-shell mission-grid"><article><span>Our mission</span><h2>To make authentic African food products accessible through dependable sourcing, quality-focused supply and customer-centred service.</h2></article><article><span>Our vision</span><h2>To become a trusted international name for Nigerian and African food sourcing and supply.</h2></article></div></section>
    <section className="principles-section section-pad home-route-stage" data-route="03 / buyer promise"><div className="site-shell"><div className="section-head compact-head"><div><div className="route-kicker"><span /> The values we carry</div><h2>Authenticity, in every <em>handover.</em></h2></div></div><div className="principles-grid principles-grid-six">{values.map(({ icon: Icon, title, copy }, index) => <article className="principle" key={title}><span className="principle-no">0{index + 1}</span><span className="principle-stage">Buyer promise / 0{index + 1}</span><Icon size={26} /><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="brief-section section-pad"><div className="site-shell brief-card"><div><span className="brief-label">A reliable source, built for conversation</span><h2>Looking for Nigerian and African food products?</h2></div><Link href="/contact" className="button button-saffron">Request a quote <ArrowUpRight size={18} /></Link></div></section></main><SiteFooter /></div>;
}
