/**
 * Meridian Pantry export page: an explicit Nigerian-food wholesale journey with visible route
 * steps and trade-ready, non-fabricated sourcing language.
 */
import { ArrowUpRight, ClipboardCheck, FileCheck2, MessageCircle, PackageCheck, PlaneTakeoff } from "lucide-react";
import { Link } from "wouter";
import { PageLead, SiteFooter, SiteHeader } from "@/components/SiteLayout";
import { whatsappEnquiryUrl } from "@/lib/contactDetails";

const botanicalImage = "/manus-storage/karossy-botanical-detail_d9ef6275.jpg";
const steps = [{ icon: ClipboardCheck, label: "01", title: "Submit your requirements", copy: "Tell us the product, quantity, packaging preference and destination that matter." }, { icon: PackageCheck, label: "02", title: "We review product and quantity", copy: "We review current product availability and suitable supply options for your request." }, { icon: FileCheck2, label: "03", title: "We confirm supply options", copy: "We clarify the product, quantity, packaging and destination considerations that apply." }, { icon: PlaneTakeoff, label: "04", title: "We provide a quotation", copy: "Where suitable, we share a quotation and agree order and delivery arrangements with you." }];

export default function Export() {
  return <div className="app-shell page-shell"><SiteHeader /><main><PageLead eyebrow="Export & wholesale" title={<>Your partner for Nigerian and African food supply.</>} description="Karossy Foods supports businesses seeking reliable access to Nigerian and African food products." bannerImage="/manus-storage/karossy-palm-oil-condiments_ec23c1b7.jpg" bannerPosition="center 52%" bannerVariant="export" />
    <section className="export-intro export-intro-media"><div className="site-shell export-intro-grid"><div className="export-badge"><span>From Nigeria<br />to your market</span><strong>KF</strong></div><div className="export-intro-content"><p className="large-quote">“Supply should begin with the right product conversation, not a one-size-fits-all promise.”</p><img src={botanicalImage} alt="African food ingredients for wholesale and export supply" /></div></div></section>
    <section className="buyers-section section-pad"><div className="site-shell buyers-grid"><div><div className="route-kicker"><span /> Who we serve</div><h2>Built for buyers who bring African food to their communities.</h2></div><div className="buyers-list"><span>African food retailers</span><span>Supermarkets</span><span>Restaurants and caterers</span><span>Wholesale distributors</span><span>Importers and food businesses</span><span>International consumers</span></div></div></section>
    <section className="steps-section section-pad"><div className="site-shell"><div className="route-kicker"><span /> The quote process</div><div className="steps-list">{steps.map(({ icon: Icon, label, title, copy }) => <article className="export-step" key={label}><span className="step-no">{label}</span><div className="step-icon"><Icon size={23} /></div><div><h2>{title}</h2><p>{copy}</p></div><div className="step-connector" aria-hidden="true" /></article>)}</div></div></section>
    <section className="service-section"><div className="site-shell service-grid"><div><div className="route-kicker route-kicker-light"><span /> Supply conversations we welcome</div><h2>Wholesale, export<br />and <em>custom sourcing.</em></h2></div><div className="service-list"><span>Bulk supply structured around product, quantity, packaging and destination</span><span>International sourcing enquiries subject to product and market requirements</span><span>Distributor partnership enquiries</span><span>Specific Nigerian product and commercial quantity requests</span></div></div></section>
    <section className="brief-section section-pad"><div className="site-shell brief-card"><div><span className="brief-label">Bring the destination</span><h2>We will help you explore suitable supply options.</h2><p>Send your requirements to start a detailed wholesale or export conversation.</p></div><div className="brief-actions"><Link href="/contact" className="button button-saffron">Request a quote <ArrowUpRight size={18} /></Link><a href={whatsappEnquiryUrl("Hello Karossy Foods, I am interested in wholesale or export supply. I would like to share my product and destination requirements.")} target="_blank" rel="noreferrer" className="text-button">Chat on WhatsApp <MessageCircle size={17} /></a></div></div></section></main><SiteFooter /></div>;
}
