/** Meridian Pantry product page: a quote-led sourcing brief that pairs tactile origin imagery with buyer-ready commercial prompts. */
import { ArrowLeft, ArrowUpRight, Check, MessageCircle, PackageOpen, Route, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import NotFound from "@/pages/NotFound";
import { Breadcrumbs, SiteFooter, SiteHeader } from "@/components/SiteLayout";
import { commercialSpecificationGroups, productCategories } from "@/lib/productCatalogue";
import "@/styles/product-detail.css";

const mark = "/manus-storage/karossy-logomark_32223915.png";

export default function ProductDetail() {
  const [, params] = useRoute("/products/:slug");
  const product = productCategories.find((entry) => entry.slug === params?.slug);
  if (!product) return <NotFound />;

  const whatsappMessage = encodeURIComponent(`Hello Karossy Foods, I am interested in ${product.name}. I would like to know availability, price, pack size and wholesale/export options.`);

  return <div className={`app-shell product-detail-page product-detail-${product.slug}`}><SiteHeader inverse /><main>
    <section className="product-detail-hero"><div className="site-shell product-detail-hero-grid"><div className="product-detail-copy"><Breadcrumbs inverse items={[{ label: "Our products", href: "/products" }, { label: product.name }]} /><Link href="/products" className="detail-back"><ArrowLeft size={16} /> Back to all products</Link><div className="detail-kicker"><Route size={15} /> Karossy sourcing route / {product.label}</div><h1>{product.name}</h1><p>{product.summary}</p><p className="detail-buyer-focus">{product.buyerFocus}</p><div className="detail-hero-actions"><Link href="/contact" className="button button-saffron">Start a supply brief <ArrowUpRight size={17} /></Link><a href={`https://wa.me/2348036481214?text=${whatsappMessage}`} target="_blank" rel="noreferrer" className="text-button text-button-light">Ask the export desk <MessageCircle size={17} /></a></div></div><div className="detail-image-wrap"><img src={product.image} alt={product.imageAlt} /><div className="detail-image-seal"><img src={mark} alt="" /><span>Source → buyer</span></div><span className="detail-image-route">{product.routeNote}</span></div></div></section>
    <section className="detail-intro section-pad" data-route="01 / buyer brief"><div className="site-shell detail-intro-grid"><div><div className="route-kicker"><span /> The buyer brief</div><h2>Built around the product,<br /><em>quantity and destination.</em></h2></div><div><p>Karossy Foods considers each enquiry in relation to the product required, the quantity, the preferred packaging and the intended market. Share your requirements and our team will confirm suitable availability and supply options.</p><div className="detail-origin-line"><ShieldCheck size={18} /><span>Premium African foods, sourced from Nigeria.</span></div></div></div></section>
    <section className="detail-spec-section" data-route="02 / commercial brief"><div className="site-shell"><div className="detail-section-head"><div><div className="route-kicker"><span /> Product information</div><h2>Commercial details,<br /><em>available on request.</em></h2></div><p>Exact pack sizes, ingredients, shelf life, storage requirements and commercial terms vary by product and market. Request the detail relevant to your sourcing brief.</p></div><div className="detail-spec-grid">{commercialSpecificationGroups.map((group) => <article key={group.title} className="detail-spec-card"><div className="detail-spec-icon"><PackageOpen size={21} /></div><h3>{group.title}</h3><dl>{group.items.map((item) => <div key={item}><dt>{item}</dt><dd>Available on request</dd></div>)}</dl></article>)}</div><div className="detail-note"><img src={mark} alt="" /><p>To receive product-specific information, tell us the product, preferred pack format, quantity and destination. Our team will review the relevant supply options with you.</p></div></div></section>
    <section className="detail-range section-pad" data-route="03 / category range"><div className="site-shell detail-range-grid"><div><div className="route-kicker"><span /> Category range</div><h2>What buyers can<br /><em>ask us to source.</em></h2></div><div className="detail-range-list">{product.items.map((item) => <span key={item}><Check size={17} /> {item}</span>)}<span><Check size={17} /> Commercial pack and quantity options on request</span><span><Check size={17} /> Retail, wholesale and export supply discussions</span></div></div></section>
    <section className="detail-cta" data-route="04 / export handover"><div className="site-shell detail-cta-grid"><div><span>Ready when you are</span><h2>Tell us the crop, quantity<br />and destination.</h2><p>We’ll help shape the export brief.</p></div><div className="detail-cta-actions"><Link href="/contact" className="button button-saffron">Request a product quote <ArrowUpRight size={17} /></Link><a href={`https://wa.me/2348036481214?text=${whatsappMessage}`} target="_blank" rel="noreferrer" className="text-button text-button-light">Chat on WhatsApp <MessageCircle size={17} /></a></div></div></section>
  </main><SiteFooter /></div>;
}
