/**
 * Meridian Pantry catalogue: real imagery, route-led category navigation, and sensory export dossiers
 * combine buyer-focused product discovery with clear editable commercial information.
 */
import { ArrowUpRight, Check, Leaf, MessageCircle, PackageOpen, Route } from "lucide-react";
import { Link } from "wouter";
import { PageLead, SiteFooter, SiteHeader } from "@/components/SiteLayout";
import "@/styles/catalogue-enhancement.css";
import "@/styles/dossier-expansion.css";

const botanicalImage = "/manus-storage/karossy-botanical-detail_d9ef6275.jpg";
const mark = "/manus-storage/karossy-logomark_32223915.png";

const assortment = [
  { slug: "kilishi", name: "Kilishi & dried meat", note: "Traditional Nigerian dried meat products and African meat snacks.", items: ["Kilishi", "Dried meat snacks"], className: "assortment-fruit", image: "/manus-storage/karossy-kilishi-dried-meat_72d30bf1.jpg", imageAlt: "Nigerian dried meat arranged in a woven basket", label: "Dried meat" },
  { slug: "palm-oil", name: "Palm oil & condiments", note: "Nigerian palm oil and traditional cooking ingredients.", items: ["Nigerian palm oil", "Cooking condiments"], className: "assortment-botanical", image: "/manus-storage/karossy-palm-oil-condiments_ec23c1b7.jpg", imageAlt: "Nigerian palm oil and cooking condiments", label: "Cooking essentials" },
  { slug: "garri", name: "Garri & cassava products", note: "Ijebu Garri and other cassava-based staples.", items: ["Ijebu Garri", "Cassava staples"], className: "assortment-grain", image: "/manus-storage/karossy-garri-cassava_e23232ee.jpg", imageAlt: "Ijebu Garri in a wooden bowl with cassava", label: "Nigerian staples" },
  { slug: "dried-fish", name: "Dried fish & seafood", note: "Selected dried fish products for African food markets.", items: ["Dried fish", "Seafood selections"], className: "assortment-botanical", image: "/manus-storage/karossy-dried-fish-seafood_77f4d1c2.jpg", imageAlt: "Selected dried fish and seafood in a woven tray", label: "Seafood selection" },
  { slug: "nuts-seeds", name: "Nuts & seeds", note: "African nuts and seeds for retail and wholesale buyers.", items: ["Nuts", "Seeds"], className: "assortment-grain", image: "/manus-storage/karossy-nuts-seeds_f8b3f1be.jpg", imageAlt: "African nuts and seeds arranged in woven bowls", label: "Natural pantry" },
  { slug: "spices", name: "Spices & traditional ingredients", note: "Authentic ingredients used in Nigerian and African cooking.", items: ["Spices", "Traditional ingredients"], className: "assortment-fruit", image: "/manus-storage/karossy-spices-traditional-ingredients_3d54b592.jpg", imageAlt: "African spices and traditional cooking ingredients", label: "Aromatic pantry" },
  { slug: "other-african-foods", name: "Other African food products", note: "Additional authentic African food products for suitable enquiries.", items: ["Product range on request", "Market-led selections"], className: "assortment-botanical", image: "/manus-storage/karossy-african-food-selection_44230189.jpg", imageAlt: "Curated selection of African pantry ingredients", label: "More to explore" },
];

function PackSpecification() {
  return <div className="pack-specs"><div className="pack-spec-title"><PackageOpen size={18} /><span>Pack-size framework</span><em>Built around your brief</em></div><div className="pack-spec-groups"><div className="pack-spec-group"><span>Formats to approve</span><dl><div><dt>Retail pack size</dt><dd>Add approved size</dd></div><div><dt>Wholesale / bulk pack</dt><dd>Add approved format</dd></div><div><dt>Unit net weight</dt><dd>Add approved weight</dd></div></dl></div><div className="pack-spec-group"><span>Commercial checkpoints</span><dl><div><dt>Case configuration</dt><dd>Add approved case count</dd></div><div><dt>Packaging material</dt><dd>Add approved material</dd></div><div><dt>Minimum order quantity</dt><dd>Add approved MOQ</dd></div></dl></div></div></div>;
}

export default function Products() {
  return <div className="app-shell page-shell"><SiteHeader /><main><PageLead eyebrow="Our products" title={<>Authentic Nigerian and African food products.</>} description="Explore our range of authentic Nigerian and African food products. Product availability, packaging and quantities may vary by market and order requirements." />
    <section className="catalog-intro catalog-intro-media"><div className="site-shell catalog-intro-grid"><p className="large-quote">“The products that bring people home can also bring new customers through your door.”</p><div className="catalog-media"><img src={botanicalImage} alt="Hibiscus, sesame seeds and moringa leaves representing Karossy Foods ingredients" /><div className="catalog-note"><Leaf size={19} /><p>Tell us the product, destination and commercial requirement. We will review current availability and suitable supply options.</p></div></div></div></section>
    <section className="assortment-section section-pad"><div className="site-shell product-index-shell"><div className="product-index-route" aria-hidden="true"><span className="route-label">The ingredient route</span><i /><i /><i /><i /><i /><i /><i /></div><div className="assortment-list">{assortment.map((group) => <article className={`assortment-row ${group.className}`} key={group.name}><div className="product-index-visual"><img src={group.image} alt="" /><span><img src={mark} alt="" />{group.label}</span></div><div className="assortment-heading"><h2>{group.name}</h2><p>{group.note}</p></div><ul>{group.items.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><a href={`#category-${group.slug}`} className="round-link" aria-label={`View category dossier for ${group.name}`}><ArrowUpRight size={21} /></a></article>)}</div></div></section>
    <section className="catalogue-detail-section section-pad"><div className="site-shell"><div className="section-head category-detail-head"><div><div className="route-kicker"><span /> The Karossy product dossier</div><h2>Choose the category.<br /><em>We’ll shape the details.</em></h2></div><p>Each export dossier combines current category imagery with a structured pack-size detail for the approved information your buyers need. Add final product and commercial specifications as they are cleared for publication.</p></div><div className="category-detail-grid">{assortment.map((group) => <article id={`category-${group.slug}`} key={group.name} className={`category-detail-card ${group.className}`}><div className="category-photo-placeholder"><img src={group.image} alt={group.imageAlt} /><div className="photo-placeholder-top"><img src={mark} alt="" /><span>Karossy product visual</span></div><div className="photo-placeholder-main"><strong>{group.name}</strong><small>Authentic African ingredients, sourced with care.</small></div><div className="photo-route-caption"><Route size={14} /> Source → buyer</div></div><div className="category-specs"><div className="category-card-header"><div className="category-dossier-line"><span>Karossy export dossier</span><img src={mark} alt="" /></div><h3>{group.name}</h3><p>{group.note}</p></div><PackSpecification /><div className="category-actions"><Link href="/contact" className="button button-forest">Plan supply for this category <ArrowUpRight size={16} /></Link><a href="https://wa.me/2348036481214?text=Hello%20Karossy%20Foods%2C%20I%20am%20interested%20in%20your%20products.%20I%20would%20like%20to%20know%20availability%2C%20price%2C%20pack%20size%20and%20wholesale%2Fexport%20options." target="_blank" rel="noreferrer" className="text-button">Ask the export desk <MessageCircle size={16} /></a></div></div></article>)}</div></div></section>
    <section className="format-section"><div className="site-shell format-grid"><div className="format-copy"><div className="route-kicker route-kicker-light"><span /> Supply options</div><h2>Retail, wholesale<br />and <em>export.</em></h2></div><div className="format-list"><span>Product availability by enquiry</span><span>Pack and size options agreed for your brief</span><span>Commercial supply planning for your destination</span></div></div></section>
    <section className="brief-section section-pad"><div className="site-shell brief-card"><div><span className="brief-label">Need a product in commercial quantities?</span><h2>Bring the destination. We’ll help shape the supply brief.</h2><p>We will review availability and suitable supply options for your market.</p></div><div className="brief-actions"><Link href="/contact" className="button button-saffron">Share your sourcing brief <ArrowUpRight size={18} /></Link><a className="text-button" href="https://wa.me/2348036481214?text=Hello%20Karossy%20Foods%2C%20I%20am%20interested%20in%20your%20products.%20I%20would%20like%20to%20know%20availability%2C%20price%2C%20pack%20size%20and%20wholesale%2Fexport%20options." target="_blank" rel="noreferrer">Speak with the export desk <MessageCircle size={17} /></a></div></div></section>
  </main><SiteFooter /></div>;
}
