/** Meridian Pantry catalogue: route-led discovery and available-on-request commercial briefs link buyers to dedicated category pages. */
import { ArrowUpRight, Check, Leaf, MessageCircle, PackageOpen, Route } from "lucide-react";
import { Link } from "wouter";
import { PageLead, SiteFooter, SiteHeader } from "@/components/SiteLayout";
import { productCategories } from "@/lib/productCatalogue";
import { whatsappEnquiryUrl } from "@/lib/contactDetails";
import "@/styles/catalogue-enhancement.css";
import "@/styles/dossier-expansion.css";

const botanicalImage = "/manus-storage/karossy-botanical-detail_d9ef6275.jpg";
const mark = "/manus-storage/karossy-logomark_32223915.png";

function PackSpecification() {
  return <div className="pack-specs"><div className="pack-spec-title"><PackageOpen size={18} /><span>Commercial information</span><em>Available on request</em></div><div className="pack-spec-groups"><div className="pack-spec-group"><span>Pack & format</span><dl><div><dt>Retail pack sizes</dt><dd>Available on request</dd></div><div><dt>Wholesale / bulk packs</dt><dd>Available on request</dd></div><div><dt>Packaging format</dt><dd>Available on request</dd></div></dl></div><div className="pack-spec-group"><span>Supply & handling</span><dl><div><dt>Case configuration</dt><dd>Available on request</dd></div><div><dt>Minimum order quantity</dt><dd>Available on request</dd></div><div><dt>Storage & shelf life</dt><dd>Available on request</dd></div></dl></div></div></div>;
}

export default function Products() {
  return <div className="app-shell page-shell"><SiteHeader /><main><PageLead eyebrow="Our products" title={<>Authentic Nigerian and African food products.</>} description="Explore our range of authentic Nigerian and African food products. Product availability, packaging and quantities may vary by market and order requirements." bannerImage="/manus-storage/karossy-hero-ingredients_18d4b704.jpg" bannerPosition="center" bannerVariant="products" />
    <section className="catalog-intro catalog-intro-media"><div className="site-shell catalog-intro-grid"><p className="large-quote">“The products that bring people home can also bring new customers through your door.”</p><div className="catalog-media"><img src={botanicalImage} alt="Hibiscus, sesame seeds and moringa leaves representing Karossy Foods ingredients" /><div className="catalog-note"><Leaf size={19} /><p>Tell us the product, destination and commercial requirement. We will review current availability and suitable supply options.</p></div></div></div></section>
    <section className="assortment-section section-pad"><div className="site-shell product-index-shell"><div className="product-index-route" aria-hidden="true"><span className="route-label">The ingredient route</span><i /><i /><i /><i /><i /><i /><i /></div><div className="assortment-list">{productCategories.map((group) => <article className={`assortment-row ${group.className}`} key={group.name}><div className="product-index-visual"><img src={group.image} alt="" /><span><img src={mark} alt="" />{group.label}</span></div><div className="assortment-heading"><h2>{group.name}</h2><p>{group.summary}</p></div><ul>{group.items.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><Link href={`/products/${group.slug}`} className="round-link" aria-label={`View details for ${group.name}`}><ArrowUpRight size={21} /></Link></article>)}</div></div></section>
    <section className="catalogue-detail-section section-pad"><div className="site-shell"><div className="section-head category-detail-head"><div><div className="route-kicker"><span /> The Karossy product dossier</div><h2>Choose the category.<br /><em>We’ll shape the details.</em></h2></div><p>Each export dossier provides a direct route to category information. Commercial pack and specification details are available on request to ensure they are aligned to the product and destination market.</p></div><div className="category-detail-grid">{productCategories.map((group) => <article id={`category-${group.slug}`} key={group.name} className={`category-detail-card ${group.className}`}><div className="category-photo-placeholder"><img src={group.image} alt={group.imageAlt} /><div className="photo-placeholder-top"><img src={mark} alt="" /><span>Karossy product visual</span></div><div className="photo-placeholder-main"><strong>{group.name}</strong><small>Authentic African ingredients, sourced with care.</small></div><div className="photo-route-caption"><Route size={14} /> Source → buyer</div></div><div className="category-specs"><div className="category-card-header"><div className="category-dossier-line"><span>Karossy export dossier</span><img src={mark} alt="" /></div><h3>{group.name}</h3><p>{group.summary}</p></div><PackSpecification /><div className="category-actions"><Link href={`/products/${group.slug}`} className="button button-forest">View category details <ArrowUpRight size={16} /></Link><a href={whatsappEnquiryUrl(`Hello Karossy Foods, I am interested in ${group.name}. I would like to know availability, price, pack size and wholesale/export options.`)} target="_blank" rel="noreferrer" className="text-button">Ask the export desk <MessageCircle size={16} /></a></div></div></article>)}</div></div></section>
    <section className="format-section"><div className="site-shell format-grid"><div className="format-copy"><div className="route-kicker route-kicker-light"><span /> Supply options</div><h2>Retail, wholesale<br />and <em>export.</em></h2></div><div className="format-list"><span>Product availability by enquiry</span><span>Pack and size options confirmed for your brief</span><span>Commercial supply planning for your destination</span></div></div></section>
    <section className="brief-section section-pad"><div className="site-shell brief-card"><div><span className="brief-label">Need a product in commercial quantities?</span><h2>Bring the destination. We’ll help shape the supply brief.</h2><p>We will review availability and suitable supply options for your market.</p></div><div className="brief-actions"><Link href="/contact" className="button button-saffron">Share your sourcing brief <ArrowUpRight size={18} /></Link><a className="text-button" href={whatsappEnquiryUrl("Hello Karossy Foods, I am interested in your products. I would like to know availability, price, pack size and wholesale/export options.")} target="_blank" rel="noreferrer">Speak with the export desk <MessageCircle size={17} /></a></div></div></section>
  </main><SiteFooter /></div>;
}
