/**
 * Meridian Pantry catalogue: tactile, provenance-led export dossiers reserve polished fields
 * for approved category photography and detailed pack information without making the page feel administrative.
 */
import { ArrowUpRight, Check, ImagePlus, Leaf, MessageCircle, PackageOpen, Route } from "lucide-react";
import { Link } from "wouter";
import { PageLead, SiteFooter, SiteHeader } from "@/components/SiteLayout";
import "@/styles/catalogue-enhancement.css";

const botanicalImage = "/manus-storage/karossy-botanical-detail_d9ef6275.jpg";
const mark = "/manus-storage/karossy-logomark_32223915.png";

const assortment = [
  { name: "Kilishi & dried meat", note: "Traditional Nigerian dried meat products and African meat snacks.", items: ["Kilishi", "Dried meat snacks"], className: "assortment-fruit", imageNote: "Add approved Kilishi, dried-meat or packaging imagery" },
  { name: "Palm oil & condiments", note: "Nigerian palm oil and traditional cooking ingredients.", items: ["Nigerian palm oil", "Cooking condiments"], className: "assortment-botanical", imageNote: "Add approved palm oil and condiment imagery" },
  { name: "Garri & cassava products", note: "Ijebu Garri and other cassava-based staples.", items: ["Ijebu Garri", "Cassava staples"], className: "assortment-grain", imageNote: "Add approved Garri, cassava or packaging imagery" },
  { name: "Dried fish & seafood", note: "Selected dried fish products for African food markets.", items: ["Dried fish", "Seafood selections"], className: "assortment-botanical", imageNote: "Add approved dried fish or seafood imagery" },
  { name: "Nuts & seeds", note: "African nuts and seeds for retail and wholesale buyers.", items: ["Nuts", "Seeds"], className: "assortment-grain", imageNote: "Add approved nuts, seeds or pack imagery" },
  { name: "Spices & traditional ingredients", note: "Authentic ingredients used in Nigerian and African cooking.", items: ["Spices", "Traditional ingredients"], className: "assortment-fruit", imageNote: "Add approved spices and ingredient imagery" },
  { name: "Other African food products", note: "Additional authentic African food products for suitable enquiries.", items: ["Product range on request", "Market-led selections"], className: "assortment-botanical", imageNote: "Add approved additional product imagery" },
];

function PackSpecification() {
  return <div className="pack-specs"><div className="pack-spec-title"><PackageOpen size={18} /><span>Pack-size framework</span><em>Quote-led</em></div><dl><div><dt>Retail pack size</dt><dd>Add approved size</dd></div><div><dt>Wholesale / bulk pack</dt><dd>Add approved format</dd></div><div><dt>Case configuration</dt><dd>Add approved case count</dd></div><div><dt>Unit net weight</dt><dd>Add approved weight</dd></div><div><dt>Packaging material</dt><dd>Add approved material</dd></div><div><dt>Minimum order quantity</dt><dd>Add approved MOQ</dd></div></dl></div>;
}

export default function Products() {
  return <div className="app-shell page-shell"><SiteHeader /><main><PageLead eyebrow="Our products" title={<>Authentic Nigerian and African food products.</>} description="Explore our range of authentic Nigerian and African food products. Product availability, packaging and quantities may vary by market and order requirements." />
    <section className="catalog-intro catalog-intro-media"><div className="site-shell catalog-intro-grid"><p className="large-quote">“The products that bring people home can also bring new customers through your door.”</p><div className="catalog-media"><img src={botanicalImage} alt="Hibiscus, sesame seeds and moringa leaves representing Karossy Foods ingredients" /><div className="catalog-note"><Leaf size={19} /><p>Tell us the product, destination and commercial requirement. We will review current availability and suitable supply options.</p></div></div></div></section>
    <section className="assortment-section section-pad"><div className="site-shell assortment-list">{assortment.map((group, index) => <article className={`assortment-row ${group.className}`} key={group.name}><div className="assortment-number">{String(index + 1).padStart(2, "0")}</div><div className="assortment-heading"><h2>{group.name}</h2><p>{group.note}</p></div><ul>{group.items.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><a href={`#category-${index + 1}`} className="round-link" aria-label={`View category dossier for ${group.name}`}><ArrowUpRight size={21} /></a></article>)}</div></section>
    <section className="catalogue-detail-section section-pad"><div className="site-shell"><div className="section-head category-detail-head"><div><div className="route-kicker"><span /> The Karossy product dossier</div><h2>Choose the category.<br /><em>We’ll shape the details.</em></h2></div><p>Each export dossier prepares a visual field and structured pack-size detail for the approved information your buyers need. Add final product photography and commercial specifications as they are cleared for publication.</p></div><div className="category-detail-grid">{assortment.map((group, index) => <article id={`category-${index + 1}`} key={group.name} className={`category-detail-card ${group.className}`}><div className="category-photo-placeholder"><div className="photo-placeholder-top"><img src={mark} alt="" /><span>Karossy product visual</span></div><div className="photo-placeholder-main"><ImagePlus size={26} /><strong>{group.name}</strong><small>{group.imageNote}</small></div><div className="photo-route-caption"><Route size={14} /> Source → buyer</div><span className="photo-slot-index">{String(index + 1).padStart(2, "0")}</span></div><div className="category-specs"><div className="category-card-header"><div className="category-dossier-line"><span>Export dossier / {String(index + 1).padStart(2, "0")}</span><img src={mark} alt="" /></div><h3>{group.name}</h3><p>{group.note}</p></div><PackSpecification /><div className="category-actions"><Link href="/contact" className="button button-forest">Request a quote <ArrowUpRight size={16} /></Link><a href="https://wa.me/2348036481214?text=Hello%20Karossy%20Foods%2C%20I%20am%20interested%20in%20your%20products.%20I%20would%20like%20to%20know%20availability%2C%20price%2C%20pack%20size%20and%20wholesale%2Fexport%20options." target="_blank" rel="noreferrer" className="text-button">Ask about this category <MessageCircle size={16} /></a></div></div></article>)}</div></div></section>
    <section className="format-section"><div className="site-shell format-grid"><div className="format-copy"><div className="route-kicker route-kicker-light"><span /> Supply options</div><h2>Retail, wholesale<br />and <em>export.</em></h2></div><div className="format-list"><span>01 / Product availability by enquiry</span><span>02 / Pack and size options agreed for your brief</span><span>03 / Commercial supply planning for your destination</span></div></div></section>
    <section className="brief-section section-pad"><div className="site-shell brief-card"><div><span className="brief-label">Need a product in commercial quantities?</span><h2>Request a quote with your destination, quantity and packaging requirements.</h2><p>We will review availability and suitable supply options for your market.</p></div><div className="brief-actions"><Link href="/contact" className="button button-saffron">Request a quote <ArrowUpRight size={18} /></Link><a className="text-button" href="https://wa.me/2348036481214?text=Hello%20Karossy%20Foods%2C%20I%20am%20interested%20in%20your%20products.%20I%20would%20like%20to%20know%20availability%2C%20price%2C%20pack%20size%20and%20wholesale%2Fexport%20options." target="_blank" rel="noreferrer">Chat on WhatsApp <MessageCircle size={17} /></a></div></div></section>
  </main><SiteFooter /></div>;
}
